Allow releases from branches

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -22,11 +22,11 @@ jobs:
     name: Check inputs
     runs-on: ubuntu-latest
     steps:
-      - name: Check release branch
-        if: github.ref_name != 'master'
-        run: |
-          echo "::error::Release must be made on the master branch"
-          exit 1
+      # - name: Check release branch
+      #   if: github.ref_name != 'master'
+      #   run: |
+      #     echo "::error::Release must be made on the master branch"
+      #     exit 1
       - name: Check version format
         shell: bash
         if: ${{ !contains(fromJSON('["major", "minor", "patch"]'), inputs.version) }}
